# D:/code/LearnHub/docker-compose.yml
services:
  backend:
    build:
      context: ./learnhub-backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - API_TITLE=${API_TITLE}
      - DEBUG=${DEBUG}
    ports:
      - "8000:8000" 
    networks:
      - learnhub-network

  frontend:
    build:
      context: ./learnhub-frontend 
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    networks:
      - learnhub-network

  nginx:
    build:
      context: ./nginx 
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80" 
    depends_on:
      - frontend
      - backend
    networks:
      - learnhub-network

networks:
  learnhub-network:
    driver: bridge